'use client';

import { useEffect } from "react";

const BOTPRESS_INJECT_URL =
  "https://cdn.botpress.cloud/webchat/v3.7/inject.js";
const BOTPRESS_CONFIG_URL =
  "https://files.bpcontent.cloud/2026/07/12/16/20260712163416-V9EJYWEN.js";

declare global {
  interface Window {
    botpress?: {
      open?: () => void;
      close?: () => void;
      sendEvent?: (event: unknown) => void;
      sendMessage?: (message: string) => void;
      on?: (
        event: string,
        handler: (...args: unknown[]) => void,
      ) => (() => void) | void;
    };
    __roofrayBotpressLoading?: boolean;
    __roofrayBotpressLoaded?: boolean;
  }
}

export default function BotpressProvider() {
  useEffect(() => {
    if (window.__roofrayBotpressLoaded || window.__roofrayBotpressLoading) {
      return;
    }

    window.__roofrayBotpressLoading = true;

    const loadScript = (src: string, id: string) =>
      new Promise<void>((resolve, reject) => {
        const existing = document.getElementById(id) as HTMLScriptElement | null;

        if (existing) {
          if (existing.dataset.loaded === "true") {
            resolve();
            return;
          }

          existing.addEventListener("load", () => resolve(), { once: true });
          existing.addEventListener("error", () => reject(new Error(`Failed to load ${src}`)), {
            once: true,
          });
          return;
        }

        const script = document.createElement("script");
        script.id = id;
        script.src = src;
        script.async = true;
        script.onload = () => {
          script.dataset.loaded = "true";
          resolve();
        };
        script.onerror = () => reject(new Error(`Failed to load ${src}`));
        document.head.appendChild(script);
      });

    const initialize = async () => {
      try {
        // Load Botpress in strict order: inject.js first, then the
        // Botpress-specific configuration generated by the Botpress dashboard.
        await loadScript(BOTPRESS_INJECT_URL, "roofray-botpress-v37");
        await loadScript(BOTPRESS_CONFIG_URL, "roofray-botpress-config");

        window.__roofrayBotpressLoaded = true;
        window.dispatchEvent(new CustomEvent("roofray_botpress_ready"));

        // If Botpress exposes its initialization listener, wait for the
        // Webchat to be ready before anything tries to open/send to it.
        if (window.botpress?.on) {
          window.botpress.on("webchat:initialized", () => {
            window.dispatchEvent(new CustomEvent("roofray_botpress_initialized"));
          });
        }
      } catch (error) {
        console.error("[RoofRay] Failed to load Botpress Webchat:", error);
        window.__roofrayBotpressLoading = false;
      }
    };

    void initialize();
  }, []);

  return null;
}
